# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_seekers', models.ManyToManyField(related_name='item_seekers', to='first_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item_seekers',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
