# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180130_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hired',
        ),
    ]
