# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_user_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.DateField(null=True),
        ),
    ]
